# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90dcdce877f3aac30e7773d876fcb3c6cd4938ee2e9ddd175204c455cba071eee59d43dd69305eeb9eebf5073f6c54ae3011ee549a87843668c7021831fa24a

test:
  secret_key_base: 16e95e4a5187bc42b47cfb8e97a2d3acf903d14e6021038dd6f05c0d9e1750cd0d0414ffaebfd348219ac663fbae2dea3e01ee40edb2ea9cc5fbf9807e56c779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
